Naming/BlockParameterName:
  Description: Disallows non-descriptive block parameter names
  MinNameLength: 1
  AllowNamesEndingInNumbers: true
  ForbiddenNames: []
  Enabled: true
  Severity: Convention

Documentation/DocumentationAdmonition:
  Excluded:
    - src/**/**
  Enabled: true
