FROM --platform=${TARGETPLATFORM:-linux/amd64} alpine:edge AS build
RUN apk add --no-cache \
    cmake \
    crystal \
    gc-dev \
    gc-static \
    libjpeg-turbo-dev \
    libjpeg-turbo-static \
    libxml2-dev \
    libxml2-static \
    lua5.4-dev \
    make \
    openssl-dev \
    openssl-libs-static \
    pcre2-dev \
    pcre2-static \
    pkgconf \
    ragel \
    shards \
    upx \
    xz-dev \
    xz-static \
    yaml-dev \
    yaml-static \
    zlib-dev \
    zlib-static \
